# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from user_msgs/CannonStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CannonStatus(genpy.Message):
  _md5sum = "e31433468f551973da97c9147997bd00"
  _type = "user_msgs/CannonStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 bullet_num

uint8 capacity
float32 reload_time

bool rdy2fire
"""
  __slots__ = ['bullet_num','capacity','reload_time','rdy2fire']
  _slot_types = ['uint8','uint8','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bullet_num,capacity,reload_time,rdy2fire

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CannonStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.bullet_num is None:
        self.bullet_num = 0
      if self.capacity is None:
        self.capacity = 0
      if self.reload_time is None:
        self.reload_time = 0.
      if self.rdy2fire is None:
        self.rdy2fire = False
    else:
      self.bullet_num = 0
      self.capacity = 0
      self.reload_time = 0.
      self.rdy2fire = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2BfB().pack(_x.bullet_num, _x.capacity, _x.reload_time, _x.rdy2fire))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.bullet_num, _x.capacity, _x.reload_time, _x.rdy2fire,) = _get_struct_2BfB().unpack(str[start:end])
      self.rdy2fire = bool(self.rdy2fire)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2BfB().pack(_x.bullet_num, _x.capacity, _x.reload_time, _x.rdy2fire))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.bullet_num, _x.capacity, _x.reload_time, _x.rdy2fire,) = _get_struct_2BfB().unpack(str[start:end])
      self.rdy2fire = bool(self.rdy2fire)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BfB = None
def _get_struct_2BfB():
    global _struct_2BfB
    if _struct_2BfB is None:
        _struct_2BfB = struct.Struct("<2BfB")
    return _struct_2BfB
