// Generated by gencpp from file user_msgs/GimbalPoseDeg.msg
// DO NOT EDIT!


#ifndef USER_MSGS_MESSAGE_GIMBALPOSEDEG_H
#define USER_MSGS_MESSAGE_GIMBALPOSEDEG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace user_msgs
{
template <class ContainerAllocator>
struct GimbalPoseDeg_
{
  typedef GimbalPoseDeg_<ContainerAllocator> Type;

  GimbalPoseDeg_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  GimbalPoseDeg_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalPoseDeg_

typedef ::user_msgs::GimbalPoseDeg_<std::allocator<void> > GimbalPoseDeg;

typedef boost::shared_ptr< ::user_msgs::GimbalPoseDeg > GimbalPoseDegPtr;
typedef boost::shared_ptr< ::user_msgs::GimbalPoseDeg const> GimbalPoseDegConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::user_msgs::GimbalPoseDeg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::user_msgs::GimbalPoseDeg_<ContainerAllocator1> & lhs, const ::user_msgs::GimbalPoseDeg_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::user_msgs::GimbalPoseDeg_<ContainerAllocator1> & lhs, const ::user_msgs::GimbalPoseDeg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace user_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c66f4de7f99199dd8e863fffbef112ad";
  }

  static const char* value(const ::user_msgs::GimbalPoseDeg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc66f4de7f99199ddULL;
  static const uint64_t static_value2 = 0x8e863fffbef112adULL;
};

template<class ContainerAllocator>
struct DataType< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "user_msgs/GimbalPoseDeg";
  }

  static const char* value(const ::user_msgs::GimbalPoseDeg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# °\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::user_msgs::GimbalPoseDeg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalPoseDeg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::user_msgs::GimbalPoseDeg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::user_msgs::GimbalPoseDeg_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USER_MSGS_MESSAGE_GIMBALPOSEDEG_H
