// Generated by gencpp from file user_msgs/PID.msg
// DO NOT EDIT!


#ifndef USER_MSGS_MESSAGE_PID_H
#define USER_MSGS_MESSAGE_PID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace user_msgs
{
template <class ContainerAllocator>
struct PID_
{
  typedef PID_<ContainerAllocator> Type;

  PID_()
    : p(0.0)
    , i(0.0)
    , d(0.0)
    , i_activate(0.0)
    , out_thresh(0.0)  {
    }
  PID_(const ContainerAllocator& _alloc)
    : p(0.0)
    , i(0.0)
    , d(0.0)
    , i_activate(0.0)
    , out_thresh(0.0)  {
  (void)_alloc;
    }



   typedef float _p_type;
  _p_type p;

   typedef float _i_type;
  _i_type i;

   typedef float _d_type;
  _d_type d;

   typedef float _i_activate_type;
  _i_activate_type i_activate;

   typedef float _out_thresh_type;
  _out_thresh_type out_thresh;





  typedef boost::shared_ptr< ::user_msgs::PID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::user_msgs::PID_<ContainerAllocator> const> ConstPtr;

}; // struct PID_

typedef ::user_msgs::PID_<std::allocator<void> > PID;

typedef boost::shared_ptr< ::user_msgs::PID > PIDPtr;
typedef boost::shared_ptr< ::user_msgs::PID const> PIDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::user_msgs::PID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::user_msgs::PID_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::user_msgs::PID_<ContainerAllocator1> & lhs, const ::user_msgs::PID_<ContainerAllocator2> & rhs)
{
  return lhs.p == rhs.p &&
    lhs.i == rhs.i &&
    lhs.d == rhs.d &&
    lhs.i_activate == rhs.i_activate &&
    lhs.out_thresh == rhs.out_thresh;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::user_msgs::PID_<ContainerAllocator1> & lhs, const ::user_msgs::PID_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace user_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::user_msgs::PID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::user_msgs::PID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::user_msgs::PID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::user_msgs::PID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::user_msgs::PID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::user_msgs::PID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::user_msgs::PID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7a91d2c8b17a0071e3c8256ef5a2554";
  }

  static const char* value(const ::user_msgs::PID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7a91d2c8b17a007ULL;
  static const uint64_t static_value2 = 0x1e3c8256ef5a2554ULL;
};

template<class ContainerAllocator>
struct DataType< ::user_msgs::PID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "user_msgs/PID";
  }

  static const char* value(const ::user_msgs::PID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::user_msgs::PID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 p\n"
"float32 i\n"
"float32 d\n"
"float32 i_activate\n"
"float32 out_thresh\n"
;
  }

  static const char* value(const ::user_msgs::PID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::user_msgs::PID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
      stream.next(m.i);
      stream.next(m.d);
      stream.next(m.i_activate);
      stream.next(m.out_thresh);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::user_msgs::PID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::user_msgs::PID_<ContainerAllocator>& v)
  {
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "i: ";
    Printer<float>::stream(s, indent + "  ", v.i);
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
    s << indent << "i_activate: ";
    Printer<float>::stream(s, indent + "  ", v.i_activate);
    s << indent << "out_thresh: ";
    Printer<float>::stream(s, indent + "  ", v.out_thresh);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USER_MSGS_MESSAGE_PID_H
